Today is the 20 Day of our Machile Learning challenge where we will write a code in order to learn Machine Learning every single day.
As in recent days we practised Linear Regression from scratch with Gradient Descent applying Regularization also.
But so far I was working only with 1 feature datas let's work with multiple features.

In [50]:
#Let's read the dataset
import pandas as pd
df = pd.read_csv("../BostonHousing.csv")

In [38]:
for column in df.columns:
    #Let's go one by one in columns we will find max and min values for each column
    min_value = min(df[column])
    max_value = max(df[column])
    #Here we will write formula of minmax scaler and apply it for every row
    df[column] = df[column].apply(lambda x: (x - min_value) / (max_value - min_value))

In [51]:
for column in df.columns:
    #Let's go one by one in columns we will find max and min values for each column
    std = df[column].std()
    mean = df[column].mean()
    #Here we will write formula of standard scaler and apply it for every row
    df[column] = df[column].apply(lambda x: (x - mean) / std)

In [52]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,-0.419367,0.284548,-1.286636,-0.272329,-0.144075,0.413263,-0.119895,0.140075,-0.981871,-0.665949,-1.457558,0.440616,-1.074499,0.159528
1,-0.416927,-0.487240,-0.592794,-0.272329,-0.739530,0.194082,0.366803,0.556609,-0.867024,-0.986353,-0.302794,0.440616,-0.491953,-0.101424
2,-0.416929,-0.487240,-0.592794,-0.272329,-0.739530,1.281446,-0.265549,0.556609,-0.867024,-0.986353,-0.302794,0.396035,-1.207532,1.322937
3,-0.416338,-0.487240,-1.305586,-0.272329,-0.834458,1.015298,-0.809088,1.076671,-0.752178,-1.105022,0.112920,0.415751,-1.360171,1.181589
4,-0.412074,-0.487240,-1.305586,-0.272329,-0.834458,1.227362,-0.510674,1.076671,-0.752178,-1.105022,0.112920,0.440616,-1.025487,1.486032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.412820,-0.487240,0.115624,-0.272329,0.157968,0.438881,0.018654,-0.625178,-0.981871,-0.802418,1.175303,0.386834,-0.417734,-0.014440
502,-0.414839,-0.487240,0.115624,-0.272329,0.157968,-0.234316,0.288648,-0.715931,-0.981871,-0.802418,1.175303,0.440616,-0.500355,-0.210154
503,-0.413038,-0.487240,0.115624,-0.272329,0.157968,0.983986,0.796661,-0.772919,-0.981871,-0.802418,1.175303,0.440616,-0.982076,0.148655
504,-0.407361,-0.487240,0.115624,-0.272329,0.157968,0.724955,0.736268,-0.667776,-0.981871,-0.802418,1.175303,0.402826,-0.864446,-0.057932
505,-0.414590,-0.487240,0.115624,-0.272329,0.157968,-0.362408,0.434302,-0.612640,-0.981871,-0.802418,1.175303,0.440616,-0.668397,-1.156104

In [53]:
#Let's define our x features and our values y 
x = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
y = df[['medv']]
#These are our values

In [54]:
#As here also we will use gradient descent let's define our k and b values
import numpy as np
k = np.random.randint(1, 10, (x.shape[1], 1))
b = 3

In [5]:
#Let's define the predicted values
y_predicted = np.zeros(x.shape[0])
for column,k_weight in zip(x.columns, range(0,14)):
    y_predicted += x[column] * k[k_weight, 0]
y_predicted += b
y_predicted = pd.DataFrame(y_predicted).rename(columns={"crim" : "medv"})

In [ ]:
learning_rate = 0.0002
for i in range(1000):
    y_predicted = np.dot(x, k) + b
    mse = np.sum((y - y_predicted)**2) / len(y)
    gradient_k = 2 * np.dot(x.T, (y_predicted- y)) / len(y)
    gradient_b = 2 * np.sum(y_predicted - y) / len(y)
    k = k - learning_rate * gradient_k
    b = b - learning_rate * gradient_b[0]
    if i % 100 == 0:
        print(mse)

medv    728.560581
dtype: float64
medv    665.454678
dtype: float64
medv    609.279826
dtype: float64
medv    559.244203
dtype: float64
medv    514.647032
dtype: float64
medv    474.868104
dtype: float64
medv    439.358501
dtype: float64
medv    407.632391
dtype: float64
medv    379.259767
dtype: float64
medv    353.860019
dtype: float64

Today was the 20 day of our challenge. Today we learned how to train Linear Regression model for multiple features from scratch.